frr version 8.4_git
frr defaults traditional
hostname Core-FRR-1
no ipv6 forwarding
!
router ospf
 ospf router-id 1.1.1.1
 network 10.0.11.0/30 area 0
 network 10.0.21.0/30 area 0
 network 10.0.100.0/30 area 0
 network 10.255.0.11/32 area 0
exit
!
end