frr version 8.4_git
frr defaults traditional
hostname Dist-FRR-1
no ipv6 forwarding
!
interface eth0.10
 ip ospf passive
exit
!
interface eth0.20
 ip ospf passive
exit
!
interface eth0.99
 ip ospf passive
exit
!
router ospf
 ospf router-id 2.2.2.1
 network 10.0.11.0/30 area 0
 network 10.0.12.0/30 area 0
 network 192.168.10.0/24 area 0
 network 192.168.20.0/24 area 0
 network 192.168.99.0/24 area 0
exit
!
end