frr version 8.4_git
frr defaults traditional
hostname Dist-FRR-2
no ipv6 forwarding
!
interface eth0.10
 ip ospf passive
 vrrp 10 version 3
 vrrp 10 priority 100
 vrrp 10 advertisement-interval 1000
 vrrp 10 ip 192.168.10.1
exit
!
interface eth0.20
 ip ospf passive
 vrrp 20 version 3
 vrrp 20 priority 100
 vrrp 20 advertisement-interval 1000
 vrrp 20 ip 192.168.20.1
exit
!
interface eth0.99
 ip ospf passive
 vrrp 99 version 3
 vrrp 99 priority 100
 vrrp 99 advertisement-interval 1000
 vrrp 99 ip 192.168.99.1
exit
!
router ospf
 ospf router-id 2.2.2.2
 network 10.0.21.0/30 area 0
 network 10.0.22.0/30 area 0
 network 192.168.10.0/24 area 0
 network 192.168.20.0/24 area 0
 network 192.168.99.0/24 area 0
 network 10.255.0.22/32 area 0
exit
!
end