---
node_name: "Core-FRR-1"
node_type: "frr-router"
router_role: "core"

management:
  type: "oob"
  interface: "eth3"
  ip: "10.200.0.11/24"
  ansible_host: "10.200.0.11"

oob_management:
  interface: "eth3"
  ip: "10.200.0.11/24"

loopback_validation:
  ip: "10.255.0.11/32"
  advertised_by: "ospf"

router_id: "1.1.1.1"

interfaces:
  lo:
    description: "routed-loopback-for-validation"
    ip: "10.255.0.11/32"
  eth0:
    description: "link-to-dist-frr-1"
    ip: "10.0.11.1/30"
  eth1:
    description: "link-to-dist-frr-2"
    ip: "10.0.21.1/30"
  eth2:
    description: "link-to-edge-router"
    ip: "10.0.100.1/30"
  eth3:
    description: "oob-management"
    ip: "10.200.0.11/24"

expected_checks:
  - oob_management_ip
  - loopback_validation_ip
  - ospf_neighbors
  - ospf_routes
  - routing_table
  - ssh_from_devops_oob_only