---
node_name: "PC2"
node_type: "vpcs-endpoint"
ssh_required: false

ip: "192.168.10.12"
gateway: "192.168.10.1"
vlan: 10

expected_connectivity:
  gateway: "192.168.10.1"
  inter_vlan_peer: "192.168.20.13"