---
node_family: "openvswitch"
access_method: "ssh"
python_required: false
ansible_module_preference: "raw"

ovs_bridge: "br0"
ovs_management_interface: "mgmt0"

ovs_common_validation_commands:
  - "hostname"
  - "ip addr"
  - "ip route"
  - "ovs-vsctl show"
  - "ovs-appctl fdb/show br0"

expected_ovs_nodes:
  access-ovs-4:
    oob_ip: "10.200.0.44"
    oob_interface: "eth3"
    inband_mgmt_ip: "192.168.99.44"
    inband_mgmt_mac: "02:99:00:00:00:44"

  access-ovs-5:
    oob_ip: "10.200.0.45"
    oob_interface: "eth3"
    inband_mgmt_ip: "192.168.99.45"
    inband_mgmt_mac: "02:99:00:00:00:45"

  access-ovs-6:
    oob_ip: "10.200.0.46"
    oob_interface: "eth4"
    inband_mgmt_ip: "192.168.99.46"
    inband_mgmt_mac: "02:99:00:00:00:46"

  dist-ovs-1:
    oob_ip: "10.200.0.31"
    oob_interface: "eth4"
    inband_mgmt_ip: "192.168.99.31"
    inband_mgmt_mac: "02:99:00:00:00:31"

  dist-ovs-2:
    oob_ip: "10.200.0.32"
    oob_interface: "eth4"
    inband_mgmt_ip: "192.168.99.32"
    inband_mgmt_mac: "02:99:00:00:00:32"

  dmz-ovs-3:
    oob_ip: "10.200.0.33"
    oob_interface: "eth3"
    legacy_dmz_mgmt_ip: "172.16.50.3"
    legacy_dmz_mgmt_mac: "02:50:00:00:00:03"