options {
    directory "/var/bind";

    listen-on port 53 { any; };
    listen-on-v6 { none; };

    allow-query { any; };

    recursion no;
    dnssec-validation no;
};

zone "pfe.local" IN {
    type master;
    file "/etc/bind/db.pfe.local";
};