options {
    directory "/var/bind";

    listen-on port 53 { any; };
    listen-on-v6 { none; };

    allow-query { any; };

    recursion yes;

    forwarders {
        8.8.8.8;
        1.1.1.1;
    };
};

zone "pfe.local" IN {
    type master;
    file "/etc/bind/db.pfe.local";
};