---
- name: Validate inventory and variable consistency
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/ovs.yml
    - ../group_vars/frr.yml

  roles:
    - inventory_consistency