---
- name: Validate generated report artifacts
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/ovs.yml
    - ../group_vars/frr.yml

  roles:
    - report_artifacts_validate