#!/usr/bin/env python3
from pathlib import Path
from html import escape
from datetime import datetime
import sys

outputs = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("outputs")
outputs.mkdir(parents=True, exist_ok=True)

html_file = outputs / "index.html"
summary_file = outputs / "jenkins-html-summary.txt"

excluded_report_files = {
    "validation-gate-exit-code.txt",
}

reports = sorted(
    report
    for report in outputs.glob("*.txt")
    if report.name not in excluded_report_files
)

critical_patterns = [
    "FAILED!",
    "fatal:",
    "UNREACHABLE!",
    "ERROR!",
    "Traceback",
]

passed = []
failed = []
missing = []
rows = []

for report in reports:
    content = report.read_text(errors="replace")
    size_kb = round(report.stat().st_size / 1024, 2)

    if not content.strip():
        state = "MISSING"
        missing.append(report.name)
    elif any(pattern in content for pattern in critical_patterns):
        state = "FAILED"
        failed.append(report.name)
    else:
        state = "PASSED"
        passed.append(report.name)

    preview = chr(10).join(content.splitlines()[:18])

    rows.append(
        f"""
        <tr class="{state.lower()}">
          <td>{escape(report.name)}</td>
          <td>{escape(state)}</td>
          <td>{size_kb} KB</td>
          <td><pre>{escape(preview)}</pre></td>
        </tr>
        """
    )

status = "PASSED" if not failed and not missing else "FAILED"

html = f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>PFE Jenkins Validation Summary</title>
  <style>
    body {{
      font-family: Arial, sans-serif;
      margin: 30px;
      background: #f7f7f7;
      color: #222;
    }}
    h1 {{
      margin-bottom: 5px;
    }}
    .card {{
      background: white;
      padding: 18px;
      border-radius: 8px;
      margin-bottom: 18px;
      box-shadow: 0 1px 4px rgba(0,0,0,0.12);
    }}
    .status {{
      font-weight: bold;
      font-size: 20px;
    }}
    .passed {{
      background: #e9f8ee;
    }}
    .failed {{
      background: #fdecec;
    }}
    .missing {{
      background: #fff4df;
    }}
    table {{
      width: 100%;
      border-collapse: collapse;
      background: white;
    }}
    th, td {{
      border: 1px solid #ddd;
      padding: 10px;
      vertical-align: top;
    }}
    th {{
      background: #222;
      color: white;
    }}
    pre {{
      white-space: pre-wrap;
      word-break: break-word;
      margin: 0;
      max-height: 280px;
      overflow: auto;
    }}
  </style>
</head>
<body>
  <div class="card">
    <h1>PFE Network Validation Summary</h1>
    <p>Generated by Jenkins on {escape(datetime.now().strftime('%Y-%m-%d %H:%M:%S'))}</p>
    <p class="status">Overall status: {escape(status)}</p>
    <ul>
      <li>Total reports: {len(reports)}</li>
      <li>Passed: {len(passed)}</li>
      <li>Failed: {len(failed)}</li>
      <li>Missing/empty: {len(missing)}</li>
    </ul>
  </div>

  <table>
    <thead>
      <tr>
        <th>Report</th>
        <th>Status</th>
        <th>Size</th>
        <th>Preview</th>
      </tr>
    </thead>
    <tbody>
      {''.join(rows)}
    </tbody>
  </table>
</body>
</html>
"""

html_file.write_text(html)

summary = f"""PFE Jenkins HTML Summary
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Overall status: {status}
Total reports: {len(reports)}
Passed: {len(passed)}
Failed: {len(failed)}
Missing/empty: {len(missing)}
HTML file: {html_file}
"""

summary_file.write_text(summary)

print(f"[OK] Generated {html_file}")
print(f"[OK] Generated {summary_file}")
print(f"[INFO] Overall status: {status}")
